/**
 * Shape patterns defined as strings for easy editing.
 * Each character is a cell in a 30x30 grid context.
 */

export const SHAPE_PATTERNS: Record<string, string[]> = {
  tutorial: [
    "  X   X   X  ",
    "  X   X   X  ",
    "  X   X   X  ",
    "  X   X   X  ",
    "  X   X   X  ",
    "  X   X   X  ",
    "  X   X   X  ",
    "  X   X   X  ",
    "  X   X   X  ",
  ],
  level2: [
    " XXXXX ",
    " XXXXX ",
    " XXXXX ",
    " XXXXX ",
    " XXXXX ",
  ],
  level3: [
    "  XX   XX  ",
    " XXXXX XXXX ",
    "XXXXXXXXXXX",
    "XXXXXXXXXXX",
    " XXXXXXXXX ",
    "  XXXXXXX  ",
    "   XXXXX   ",
    "    XXX    ",
    "     X     ",
  ],
  star: [
    "        X        ",
    "       XXX       ",
    "      XXXXX      ",
    "     XXXXXXX     ",
    "    XXXXXXXXX    ",
    "XXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXX ",
    "  XXXXXXXXXXXXX  ",
    "   XXXXXXXXXXX   ",
    "    XXXXXXXXX    ",
    "   XXXXX XXXXX   ",
    "  XXXXX   XXXXX  ",
    "  XXXX     XXXX  ",
    " XXXX       XXXX ",
    " XXX         XXX ",
    " XX           XX ",
  ],
  mario: [
    "      XXXXX      ",
    "     XXXXXXXXX   ",
    "     XXXXXXXXX   ",
    "   XXXX X XX X   ",
    "  X XXXXX XX XXX ",
    "  X XXXXXXXXXXXX ",
    "  X XXXX XXXXXX  ",
    "    XXXXXXXXXX   ",
    "  XXXXX    XXXXX ",
    " XXXXXXX  XXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXX XXXXXXX XXXX",
    "XXX  XXXXXXX  XXX",
    "XXX  XXXXXXX  XXX",
    "XX   XXXXXXX   XX",
    "    XXX   XXX    ",
    "   XXXX   XXXX   ",
    "  XXXX     XXXX  ",
  ],
  donut: [
    "      XXXXX      ",
    "    XXXXXXXXX    ",
    "   XXXXXXXXXXX   ",
    "  XXXXXXXXXXXXX  ",
    " XXXXXXXXXXXXXXX ",
    " XXXXXX   XXXXXX ",
    "XXXXXX     XXXXXX",
    "XXXXXX     XXXXXX",
    "XXXXXX     XXXXXX",
    "XXXXXX     XXXXXX",
    "XXXXXX     XXXXXX",
    " XXXXXX   XXXXXX ",
    " XXXXXXXXXXXXXXX ",
    "  XXXXXXXXXXXXX  ",
    "   XXXXXXXXXXX   ",
    "    XXXXXXXXX    ",
    "      XXXXX      ",
  ],
  square: [
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX"
  ],
  rect: [
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
  ],
  cat: [
    "  X          X  ",
    " XXX        XXX ",
    " XXXX      XXXX ",
    " XXXXX    XXXXX ",
    " XXXXXXXXXXXXXX ",
    " XXXXXXXXXXXXXX ",
    " XXXXXXXXXXXXXX ",
    " XXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXX ",
    "  XXXXXXXXXXXX  ",
    "   XXXXXXXXXX   ",
    "    XXXXXXXX    ",
  ],
  apple: [
    "        XX       ",
    "       XXX       ",
    "       XX        ",
    "     XXXXXX      ",
    "   XXXXXXXXXX    ",
    "  XXXXXXXXXXXX   ",
    " XXXXXXXXXXXXXX  ",
    " XXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXX ",
    " XXXXXXXXXXXXXX  ",
    " XXXXXXXXXXXXXX  ",
    "  XXXXXXXXXXXX   ",
    "   XXXXXXXXXX    ",
    "     XXXXXX      ",
  ],
  duck: [
    "      XXXXX   ",
    "     XXXXXXX  ",
    " XX  XXXXXXX  ",
    "XXXX XXXXXXX  ",
    "XXX  XXXXX    ",
    "     XXXX     ",
    "   XXXXXXX    ",
    "  XXXXXXXXX   ",
    " XXXXXXXXXXX  ",
    "XXXXXXXXXXXXX ",
    " XXXXXXXXXXXX ",
    "  XXXXXXXXXX  ",
    "    XXXXXX    ",
  ],
  flower: [
    "     XXXX     ",
    "   XXXXXXXX   ",
    "   XXXXXXXX   ",
    "XXXX XXXXX XXXX",
    "XXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXX",
    "XXXX XXXXX XXXX",
    "   XXXXXXXX   ",
    "   XXXXXXXX   ",
    "     XXXX     ",
    "      XX      ",
    "      XX      ",
    "      XX      ",
    "      XX      ",
  ],
  diamond: [
    "       X       ",
    "      XXX      ",
    "     XXXXX     ",
    "    XXXXXXX    ",
    "   XXXXXXXXX   ",
    "  XXXXXXXXXXX  ",
    " XXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXX ",
    "  XXXXXXXXXXX  ",
    "   XXXXXXXXX   ",
    "    XXXXXXX    ",
    "     XXXXX     ",
    "      XXX      ",
    "       X       ",
  ],
  ghost: [
    "     XXXXX     ",
    "   XXXXXXXXX   ",
    "  XXXXXXXXXXX  ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " X X X X X X X ",
  ],
  crown: [
    "X           X",
    "X           X",
    "XX    X    XX",
    "XXX  XXX  XXX",
    "XXXXXXXXXXXXX",
    "XXXXXXXXXXXXX",
    "XXXXXXXXXXXXX",
    "XXXXXXXXXXXXX",
    "XXXXXXXXXXXXX",
    "XXXXXXXXXXXXX",
    "XXXXXXXXXXXXX",
  ],
  mushroom: [
    "      XXXXX      ",
    "    XXXXXXXXX    ",
    "   XXXXXXXXXXX   ",
    "  XXXXXXXXXXXXX  ",
    " XXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXX ",
    "    XXXXXXXXX    ",
    "    XXXXXXXXX    ",
    "    XXXXXXXXX    ",
    "    XXXXXXXXX    ",
    "    XXXXXXXXX    ",
    "    XXXXXXXXX    ",
  ],
  heart_standard: [
    "  XXXXX   XXXXX  ",
    " XXXXXXX XXXXXXX ",
    "XXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXX ",
    " XXXXXXXXXXXXXXX ",
    "  XXXXXXXXXXXXX  ",
    "   XXXXXXXXXXX   ",
    "    XXXXXXXXX    ",
    "     XXXXXXX     ",
    "      XXXXX      ",
    "       XXX       ",
    "        X        ",
  ],
  house: [
    "        X        ",
    "       XXX       ",
    "      XXXXX      ",
    "     XXXXXXX     ",
    "    XXXXXXXXX    ",
    "   XXXXXXXXXXX   ",
    "  XXXXXXXXXXXXX  ",
    " XXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXX   ",
    "   XXXXXXXXXXX   ",
    "   XXXXXXXXXXX   ",
    "   XXXXXXXXXXX   ",
    "   XXX     XXX   ",
    "   XXX     XXX   ",
    "   XXX     XXX   ",
  ],
  tree: [
    "       XXX       ",
    "      XXXXX      ",
    "     XXXXXXX     ",
    "    XXXXXXXXX    ",
    "   XXXXXXXXXXX   ",
    "  XXXXXXXXXXXXX  ",
    " XXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXXX",
    "     XXXXXXX     ",
    "    XXXXXXXXX    ",
    "   XXXXXXXXXXX   ",
    "  XXXXXXXXXXXXX  ",
    " XXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXXX",
    "      XXXXX      ",
    "      XXXXX      ",
    "      XXXXX      ",
    "      XXXXX      ",
    "      XXXXX      ",
  ],
  flash: [
    "        XXXXX ",
    "       XXXXXX ",
    "      XXXXXX  ",
    "     XXXXXX   ",
    "    XXXXXX    ",
    "   XXXXXX     ",
    "  XXXXXXXXXXXX",
    " XXXXXXXXXXXX ",
    "        XXXX  ",
    "       XXXX   ",
    "      XXXX    ",
    "     XXXX     ",
    "    XXXX      ",
    "   XXXX       ",
    "  XX          ",
  ],
  butterfly: [
    "X               X",
    "XX             XX",
    "XXXX         XXXX",
    "XXXXXX     XXXXXX",
    "XXXXXXXX XXXXXXXX",
    "XXXXXXXX XXXXXXXX",
    "XXXXXXX   XXXXXXX",
    "XXXXXX     XXXXXX",
    "XXXXXXX   XXXXXXX",
    "XXXXXXXX XXXXXXXX",
    "XXXXXXXX XXXXXXXX",
    "XXXXXX     XXXXXX",
    "XXXX         XXXX",
    "XX             XX",
  ],
  note: [
    "        XXXXXXX",
    "        XXXXXXX",
    "        X     X",
    "        X     X",
    "        X     X",
    "        X     X",
    "        X     X",
    "    XXXXX     X",
    "  XXXXXXX XXXXX",
    " XXXXXXXX XXXXXXX",
    " XXXXXXXX XXXXXXXX",
    "  XXXXXX  XXXXXXXX",
    "           XXXXXX "
  ],
  moon: [
    "      XXXXX    ",
    "    XXXXXXXX   ",
    "  XXXXXXXXXXX  ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXX X   ",
    " XXXXXXX       ",
    " XXXXXX        ",
    " XXXXX         ",
    " XXXXX         ",
    " XXXXXX        ",
    " XXXXXXX       ",
    " XXXXXXXXX X   ",
    " XXXXXXXXXXXXX ",
    "  XXXXXXXXXXX  ",
    "    XXXXXXXX   ",
    "      XXXXX    ",
  ],
  coffee: [
    "     XXXXX     ",
    "      X X      ",
    "     X   X     ",
    "               ",
    " XXXXXXXXXXX   ",
    " XXXXXXXXXXXX  ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXXX ",
    " XXXXXXXXXXXX  ",
    " XXXXXXXXXXX   ",
    " XXXXXXXXXXX   ",
    "  XXXXXXXXX    ",
    "  XXXXXXXXX    ",
  ]
};

export function parsePattern(pattern: string[]): { x: number; y: number }[] {
  const points: { x: number; y: number }[] = [];
  const height = pattern.length;
  const width = Math.max(...pattern.map(r => r.length));
  
  // Center it in a 30x30 grid
  const offsetX = Math.floor((30 - width) / 2);
  const offsetY = Math.floor((30 - height) / 2);

  pattern.forEach((row, y) => {
    [...row].forEach((char, x) => {
      if (char !== ' ') {
        points.push({ x: x + offsetX, y: y + offsetY });
      }
    });
  });
  
  return points;
}
